try:
	print('Hello', name)
except Exception as e:
	print('ERROR')
	print(e)